In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df18= pd.read_csv("data_raw/divorcios_2018.csv")
df19= pd.read_csv("data_raw/divorcios-2019.csv")
df20= pd.read_csv("data_raw/divorcios-2020.csv")
df21= pd.read_csv("data_raw/divorcios-2021.csv")
df22= pd.read_csv("data_raw/divorcios-2022.csv")
df23= pd.read_csv("data_raw/divorcios-2023.csv")
df24 = pd.read_csv("data_raw/divorcios-2024.csv")
df25 = pd.read_csv("data_raw/divorcios-2025.csv")

In [6]:
df18 = df18.rename(columns={
    'fecha_creacion_nr_divorcio': 'fecha_divorcio',
    'genero_1':'sexo_1',
    'genero_2':'sexo_2'
})

df19 = df19.rename(columns={
    'fecha_creacion_divorcio': 'fecha_divorcio',
    'genero_1':'sexo_1',
    'genero_2':'sexo_2'
})

In [7]:
lista_df = [df18, df19, df20, df21, df22, df23, df24, df25]

df = pd.concat(lista_df, ignore_index=True)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42720 entries, 0 to 42719
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_divorcio    42720 non-null  str
 1   sexo_1            42636 non-null  str
 2   sexo_2            42639 non-null  str
 3   fecha_matrimonio  42719 non-null  str
dtypes: str(4)
memory usage: 1.3 MB

In [9]:
df.isnull().sum()

fecha_divorcio       0
sexo_1              84
sexo_2              81
fecha_matrimonio     1
dtype: int64

In [10]:
df.describe()

       fecha_divorcio sexo_1 sexo_2 fecha_matrimonio
count           42720  42636  42639            42719
unique          11550     14     14            19427
top       2020-12-01"     M"     F"      2013-11-20"
freq               73  17135  17176               22

In [11]:
df

            fecha_divorcio      sexo_1      sexo_2     fecha_matrimonio
0      2018-01-02 08:55:31   Masculino    Femenino  2007-09-06 00:00:00
1      2018-01-02 09:01:29   Masculino    Femenino  2001-10-18 00:00:00
2      2018-01-02 09:03:32   Masculino    Femenino  1989-01-12 00:00:00
3      2018-01-02 09:05:25   Masculino    Femenino  2007-01-23 00:00:00
4      2018-01-02 09:06:54  No declara  No declara  1988-09-30 00:00:00
...                    ...         ...         ...                  ...
42715           2025-12-30  NO DECLARA  NO DECLARA           1992-07-24
42716           2025-12-30           M  NO DECLARA           1986-12-09
42717           2025-12-30           M           F           2009-03-11
42718           2025-12-30           M           F           2010-03-03
42719           2025-12-30           M           F           1994-04-21

[42720 rows x 4 columns]

In [12]:
df['fecha_divorcio'] = df['fecha_divorcio'].str.replace('"', '', regex=False)
df['fecha_matrimonio'] = df['fecha_matrimonio'].str.replace('"', '', regex=False)

In [13]:
df['fecha_matrimonio'] = df['fecha_matrimonio'].replace('0197-01-01', '1997-01-01', regex=False)

In [14]:
df['fecha_matrimonio'] = df['fecha_matrimonio'].replace('1760-01-01', '1960-01-01', regex=False)

In [15]:
df['fecha_divorcio'] = pd.to_datetime(df['fecha_divorcio'], format='mixed')
df['fecha_matrimonio'] = pd.to_datetime(df['fecha_matrimonio'], format='mixed')

In [16]:
df['fecha_divorcio'] = pd.to_datetime(df['fecha_divorcio']).dt.date
df['fecha_matrimonio'] = pd.to_datetime(df['fecha_matrimonio']).dt.date

In [17]:
df['tiempo_transcurrido'] = df['fecha_divorcio'] - df['fecha_matrimonio']

In [18]:
df['tiempo_transcurrido'] = pd.to_timedelta(df['tiempo_transcurrido'])

df['anios_matrimonio'] = (df['tiempo_transcurrido'].dt.days / 365.25).round(1)

In [19]:
df.head()

,fecha_divorcio,sexo_1,sexo_2,fecha_matrimonio,tiempo_transcurrido,anios_matrimonio
0,2018-01-02,Masculino,Femenino,2007-09-06,3771 days,10.3
1,2018-01-02,Masculino,Femenino,2001-10-18,5920 days,16.2
2,2018-01-02,Masculino,Femenino,1989-01-12,10582 days,29.0
3,2018-01-02,Masculino,Femenino,2007-01-23,3997 days,10.9
4,2018-01-02,No declara,No declara,1988-09-30,10686 days,29.3

In [20]:
df['fecha_divorcio'] = pd.to_datetime(df['fecha_divorcio'])
df['fecha_matrimonio'] = pd.to_datetime(df['fecha_matrimonio'])

df['anio_divorcio'] = df['fecha_divorcio'].dt.year
df['anio_matrimonio'] = df['fecha_matrimonio'].dt.year

In [21]:
print(df.groupby('anio_divorcio')['anios_matrimonio'].mean())

anio_divorcio
2018    18.988156
2019    19.283704
2020    19.112042
2021    19.059741
2022    20.119966
2023    20.268810
2024    19.430937
2025    19.933015
Name: anios_matrimonio, dtype: float64

In [22]:
print(df.groupby('anio_matrimonio')['anios_matrimonio'].mean())

anio_matrimonio
1931.0    89.000000
1937.0    88.200000
1946.0    76.200000
1947.0    75.200000
1948.0    74.200000
            ...
2021.0     2.834333
2022.0     2.364459
2023.0     1.680786
2024.0     1.092500
2025.0     0.600000
Name: anios_matrimonio, Length: 81, dtype: float64

In [23]:
df['anios_matrimonio'].mean()

np.float64(19.55959643250076)

In [24]:
df_anios = df.groupby('anio_divorcio').size().reset_index(name='total_divorcios')

In [25]:
df['mes_divorcio'] = df['fecha_divorcio'].dt.month

In [26]:
df_meses = df.groupby('mes_divorcio').size().reset_index(name='total_divorcios')

In [27]:
df_meses

    mes_divorcio  total_divorcios
0              1             1383
1              2             2924
2              3             4261
3              4             3751
4              5             3918
5              6             3520
6              7             3062
7              8             3896
8              9             3810
9             10             4023
10            11             4103
11            12             4069

In [28]:
df['sexo_1'].unique()

<StringArray>
[   'Masculino',   'No declara',     'Femenino',            nan,
   'Indefinido',           'F"',           'M"', 'DESCONOCIDO"',
  'NO DECLARA"',  'INDEFINIDO"',            'M',   'NO DECLARA',
            'F',  'DESCONOCIDO',   'INDEFINIDO']
Length: 15, dtype: str

In [29]:
df['sexo_1'] = df['sexo_1'].replace('NO DECLARA', 'No declara', regex=False)
df['sexo_1'] = df['sexo_1'].replace('DESCONOCIDO', 'No declara', regex=False)
df['sexo_1'] = df['sexo_1'].replace('Indefinido', 'No declara', regex=False)
df['sexo_1'] = df['sexo_1'].replace('INDEFINIDO', 'No declara', regex=False)
df['sexo_1'] = df['sexo_1'].replace('DESCONOCIDO"', 'No declara', regex=False)
df['sexo_1'] = df['sexo_1'].replace('INDEFINIDO"', 'No declara', regex=False)
df['sexo_1'] = df['sexo_1'].replace('NO DECLARA"', 'No declara', regex=False)
df['sexo_1'] = df['sexo_1'].replace('F"', 'Femenino', regex=False)
df['sexo_1'] = df['sexo_1'].replace('F', 'Femenino', regex=False)
df['sexo_1'] = df['sexo_1'].replace('M"', 'Masculino', regex=False)
df['sexo_1'] = df['sexo_1'].replace('M', 'Masculino', regex=False)

In [ ]:
def determinar_tipo_pareja(fila):

    if (fila['sexo_1'] == "No declara" or pd.isna(fila['sexo_1']) or
        fila['sexo_2'] == "No declara" or pd.isna(fila['sexo_2'])):
        return 'desconocido'

    elif fila['sexo_1'] == fila['sexo_2']:
        return 'mismo sexo'

    else:
        return 'dif sexo'

df['tipo_pareja'] = df.apply(determinar_tipo_pareja, axis=1)

In [31]:
df_tp = df.groupby('tipo_pareja').size().reset_index(name='total_divorcios')

In [32]:
df_tp

   tipo_pareja  total_divorcios
0  desconocido             6693
1     dif sexo            35895
2   mismo sexo              132

In [33]:
df.to_csv('data/dataset_final.csv', index=False)
df_tp.to_csv('data/dataset_tipos_pareja.csv', index=False)

In [34]:
df_meses.to_csv('data/dataset_meses.csv', index=False)

In [35]:
df_anios.to_csv('data/dataset_anios.csv', index=False)

In [36]:
df_tp.to_csv('data/dataset_parejas.csv', index=False)